{{- if .Values.fluentBit.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "max-weather.fluentBit.namespace" . }}
  labels:
    name: amazon-cloudwatch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentBit.serviceAccount.name }}
  namespace: {{ include "max-weather.fluentBit.namespace" . }}
  {{- with .Values.fluentBit.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
