{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: weather-api-pdb
  namespace: {{ include "max-weather.namespace" . }}
  labels:
    {{- include "max-weather.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: weather-api
{{- end }}
