{{- if .Values.weatherApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "max-weather.serviceAccountName" . }}
  namespace: {{ include "max-weather.namespace" . }}
  labels:
    {{- include "max-weather.labels" . | nindent 4 }}
  {{- with .Values.weatherApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
